name: github pages

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Give Me Your Name'
        required: false
        default: 'ImQQ'
        


jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.81.0'
          extended: true

      - name: show par
        run: echo "Hello ${{ github.event.inputs.name }}!"
        
      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PUSH_TOKEN}}
          external_repository: greeedyboy/web_nankai
          publish_branch: master # default: gh-pages
          publish_dir: ./publish_sicau
