name: github pages

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Give Me Your Name'
        required: false
        default: 'ImQQ'
      config:
        description: 'tell me the config'
        required: false
        default: 'config_sicau.toml'
      drepo:
        description: 'tell me the deploy_repo'
        required: false
        default: 'greeedyboy/web_nankai' 
      drepobranch:
        description: 'tell me the deploy_repo branch'
        required: false
        default: 'master'      

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.88.1'
          extended: true

      - name: show par
        run: echo "Hello ${{ github.event.inputs.name }}!"
        
      - name: Build
        run: hugo --config=config.toml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PUSH_TOKEN}}
          external_repository: ${{ github.event.inputs.drepo }}
          publish_branch: ${{ github.event.inputs.drepobranch }} # default: gh-pages
          force_orphan: true
          publish_dir: ./public
